title: Parchment
author: pro-panda
subtitle: The life of a frustrated engineer

url: "https://heart-leap.github.io"
baseurl: "/"

footer_only_homepage: true
footer_url: "https://twitter.com/SchifosoLo"
footer_text: "Feito por Leone, Lo Schifoso."

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:day-:month-:year-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   absolute-link: "https://pro-panda.github.io/resume.pdf"
