title: Acervo de Trabalhos do Eduardo Jefferson - AB - 1AT.
author: Leone
subtitle: Este Web-Sitio servirá para guardar e documentar os meus trabalhos no AB durante o período de ensino remoto.

url: "https://heart-leap.github.io"
baseurl: "/"

footer_only_homepage: false
footer_url: "https://twitter.com/SchifosoLo"
footer_text: "Feito por Leone, Lo Schifoso."

profile-picture: assets/profile.png
favicon_location: assets/favicon.ico

permalink: /:day-:month-:year-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "Resume"
   absolute-link: "https://pro-panda.github.io/resume.pdf"

